### ISSUE TITLE
Potential improvements

### ISSUE THREAD

**Issue by Qix-** [cris691/discohash#5]
Hey @cris691! :)

I saw your note about switching to C - I think that's a great idea, especially for anything cryptography-related (due to the ability to bind to other languages a bit easier).

Here are a few improvements I thought of just at first glance - let me know what you think. I'd be happy to put the work in.

- [ ] Switch to C
- [ ] Switch to an instanced state rather than using a global state
- [ ] Use CMake to export a library target (see below)
- [ ] `clang-tidy` the project so the formatting is consistent

Using CMake would allow the library to:
- export a library target with all include paths and everything attached; CMake is fairly standard nowadays and it'd make adoption _much_ easier.
- set up proper test targets so that discohash tests can be run alongside consumers' tests.
- add the Node.JS targets and set up other targets as well (perhaps CPython and lua targets? entirely up to you)
- properly determine OpenMP availability and the proper compiler flags in a more cross-platform way (for whenever you want to do the parallel hashing implementation)
- create a standardized way for others to contribute to the project

None of this would touch the functionality/logic/algorithm at all - I'll leave that up to you (the professional)!

If this sounds good to you (or if parts of it do) just let me know and I can fire off some PRs :)

**Comment by cris691** [comment]
@Qix- , all these sound great!

I don't anticipate any issues for most of them, so if you want to launch in, I welcome the work. Thank you so much.

The only one I don't really understand is instanced state instead of global state, so when I see the PR, I might need to think more about it, but I expect it will be fine.

I'm particularly loving the idea of using cmake and exporting a library target. Because that means we can integrate easily.

**Comment by cris691** [comment]
Also, bindings to other targets like Node, CPython and Lua is such a great idea. I like it and I'm very impressed.

**Comment by cris691** [comment]
@Qix- did you give up on these ideas? I know you've been on a holiday/enjoyed some time off, and seems like you're super busy now. Should I close this?

**Comment by Qix-** [comment]
No definitely will get to this, just taking a break from OSS this week. Have some family matters to attend to ^^ will be back soon.

**Comment by cris691** [comment]
Take care, @Qix- see you soon 😃

**Comment by Qix-** [comment]
No need to close :) let's close it when the PR lands ^^

**Comment by cris691** [comment]
This is taking a bit too long. Might reopen if you land the PRs you planned for this.
