### ISSUE TITLE
clarifying benchmark comparisons

### ISSUE THREAD

**Issue by oconnor663** [cris691/discohash#6]
The README mentions that:

> ECRYPT benchmark is 4x faster than BLAKE3

Could you clarify which machine that's on, and for which input sizes? The [first set of SUPERCOP AVX-512 results for BLAKE3](https://bench.cr.yp.to/results-hash.html#amd64-ygritte) were published yesterday.

**Comment by cris691** [comment]
Hey @oconnor663 !

> Could you clarify which machine that's on, and for which input sizes? 

It's a variety. If you like to add something to the README, I'll welcome your PR.

> The first set of SUPERCOP AVX-512 results for BLAKE3 were published yesterday.

AVX is interesting. I don't know how to use it.
